name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  # Deploy job
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages enviroment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - name: Build
        run: pnpm run docs:build
      - uses: actions/configure-pages@v2

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
